name: go-cache

up:
  - go:
      version: "1.15.12"
      modules: true
      tools:
        - github.com/alecthomas/gometalinter
        # gosumcheck is not installed by gometalinter
        - github.com/haya14busa/gosum/cmd/gosumcheck
  - custom:
        name: Load dependencies
        met?: go mod tidy
        meet: go mod tidy
  - railgun

commands:
  test: go test -race ./...
  style:
    run: bin/style
    desc: Static verification using gometalinter or autofix issues when possible.
    syntax:
      optional: --fix
